const { Route } = require('express')
const express = require('express')
const { verifyToken } = require('../Helpers/VerifyToken')
const Router = express.Router()
const multerUpload = require('../Middleware/Multer')
const UserController = require('./../Controllers/UserController')
const jwtVerify = require('./../Middleware/JWT')

Router.post('/register', UserController.register)
Router.post('/getusername', UserController.getUsername)
Router.post('/getemail', UserController.getEmail)
Router.patch('/confirmation', jwtVerify, UserController.confirmation)
Router.post('/login', UserController.login)
Router.get('/keeplogin', verifyToken, UserController.keeplogin)
Router.post('/resend', jwtVerify, UserController.resend)
Router.post('/getuserdetail', jwtVerify, UserController.getUserDetail)
Router.post('/edituserdetail', jwtVerify, UserController.editUserDetail)
Router.post('/editprofilepic', jwtVerify, multerUpload.single("photo"), UserController.editProfilePic)

module.exports = Router