const { Route } = require('express')
const express = require('express')
const { verifyToken } = require('../Helpers/VerifyToken')
const Router = express.Router()
const multerUpload = require('../Middleware/Multer')
const UserController = require('./../Controllers/UserController')
const jwtVerify = require('./../Middleware/JWT')

Router.post('/register', UserController.register)
Router.post('/getusername', UserController.getUsername)
Router.post('/getemail', UserController.getEmail)
Router.post('/getpassword', UserController.getPassword)
Router.post('/getuserdata', jwtVerify, UserController.getUserData)
Router.patch('/confirmation', jwtVerify, UserController.confirmation)
Router.post('/login', UserController.login)
Router.post('/resend', jwtVerify, UserController.resend)
Router.get('/keeplogin', verifyToken, UserController.keeplogin)
Router.post('/sendresetpasswordmail', UserController.sendResetPasswordMail)
Router.post('/resetpassword', jwtVerify, UserController.resetPassword)
Router.post('/changepassword', jwtVerify, UserController.changePassword)
Router.post('/getuserdetail', jwtVerify, UserController.getUserDetail)
Router.post('/edituserdetail', jwtVerify, UserController.editUserDetail)
Router.post('/editprofilepic', jwtVerify, multerUpload.single("photo"), UserController.editProfilePic)
Router.post('/searchuser', jwtVerify, UserController.searchUser)

module.exports = Router